name: Fast Parallel Build APKs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      android_home: ${{ steps.set_android_home.outputs.android_home }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip python3-setuptools python3-wheel \
            build-essential libssl-dev libffi-dev \
            libsqlite3-dev libbz2-dev zlib1g-dev \
            autoconf automake libtool pkg-config

      - name: Install Android SDK & Build-tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools latest
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "cmdline-tools;latest"
          echo "::set-output name=android_home::$HOME/android-sdk"

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython

  build_generator:
    runs-on: ubuntu-latest
    needs: setup
    env:
      ANDROID_HOME: $HOME/android-sdk
      PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/34.0.0:$PATH
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build QR_Generator APK
        run: |
          cd QR_Generator
          buildozer android debug --ignore-setup-py --verbose

      - name: Upload QR_Generator APK
        uses: actions/upload-artifact@v4
        with:
          name: QR_Generator-APK
          path: QR_Generator/bin/*.apk

  build_scanner:
    runs-on: ubuntu-latest
    needs: setup
    env:
      ANDROID_HOME: $HOME/android-sdk
      PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/34.0.0:$PATH
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build QR_Scanner APK
        run: |
          cd QR_Scanner
          buildozer android debug --ignore-setup-py --verbose

      - name: Upload QR_Scanner APK
        uses: actions/upload-artifact@v4
        with:
          name: QR_Scanner-APK
          path: QR_Scanner/bin/*.apk
