name: Build and Sign APKs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Cache Buildozer directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-${{ runner.os }}-cache

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git python3-pip openjdk-11-jdk unzip wget zip autoconf libtool automake pkg-config build-essential

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Download Android Command Line Tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          rm cmdline-tools.zip

      - name: Accept licenses and install SDK & build-tools
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Build and Sign QR Generator APK
        run: |
          cd QR_Generator
          buildozer android debug
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${{ github.workspace }}/keystore.jks bin/YourAppName-debug.apk $KEY_ALIAS -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD

      - name: Build and Sign QR Scanner APK
        run: |
          cd QR_Scanner
          buildozer android debug
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${{ github.workspace }}/keystore.jks bin/YourAppName-debug.apk $KEY_ALIAS -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: QR_APKs
          path: |
            QR_Generator/bin/*.apk
            QR_Scanner/bin/*.apk
