name: Build QR Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tar unzip wget openjdk-17-jdk build-essential autoconf libtool pkg-config

    # 2. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 3. Set up Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 4. Install pip requirements
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython pillow qrcode pyzbar kivy

    # 5. Build QR Generator APK
    - name: Build QR Generator APK
      working-directory: QR_Generator
      run: |
        buildozer android debug

    # 6. Build QR Scanner APK
    - name: Build QR Scanner APK
      working-directory: QR_Scanner
      run: |
        buildozer android debug

    # 7. Upload APKs as artifacts
    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: QR_APKs
        path: |
          QR_Generator/bin/*.apk
          QR_Scanner/bin/*.apk
