name: Build APKs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip python3-setuptools python3-wheel \
            build-essential libssl-dev libffi-dev \
            libsqlite3-dev libbz2-dev zlib1g-dev \
            autoconf automake libtool pkg-config

      - name: Install Android SDK & build-tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          mv cmdline-tools latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APKs in parallel (verbose)
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          # Run generator and scanner builds in background with verbose output
          (cd QR_Generator && buildozer -v android debug || (echo "Generator build failed" && cat .buildozer/android/platform/build-*/*/build-output.txt || true)) &
          (cd QR_Scanner && buildozer -v android debug || (echo "Scanner build failed" && cat .buildozer/android/platform/build-*/*/build-output.txt || true)) &
          wait

      - name: Find APKs
        run: |
          echo "Searching for APKs..."
          find . -type f -name "*.apk" -print
          echo "Dumping build logs (if available)..."
          find . -type f -name "build-output.txt" -exec echo "---- {} ----" \; -exec cat {} \; || true

