name: Build QR Apps APKs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apks:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install cython buildozer kivy pillow qrcode pyzbar

      # Step 4: Build QR Generator APK
      - name: Build QR Generator APK
        working-directory: QR_Generator
        run: |
          buildozer android debug

      # Step 5: Upload QR Generator APK
      - name: Upload QR Generator APK
        uses: actions/upload-artifact@v4
        with:
          name: QR_Generator_APK
          path: QR_Generator/bin/*.apk

      # Step 6: Build QR Scanner APK
      - name: Build QR Scanner APK
        working-directory: QR_Scanner
        run: |
          buildozer android debug

      # Step 7: Upload QR Scanner APK
      - name: Upload QR Scanner APK
        uses: actions/upload-artifact@v4
        with:
          name: QR_Scanner_APK
          path: QR_Scanner/bin/*.apk

